# Generated by Django 5.2.4 on 2025-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'created_at'], name='accounts_pa_user_id_c7ab27_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'is_verified'], name='accounts_pa_user_id_85dd30_idx'),
        ),
    ]
