# Generated by Django 5.2.4 on 2025-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_joinrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
    ]
