# Generated by Django 5.2.4 on 2025-08-04 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp_consumed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSecurityLog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=100)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'endpoint'], name='accounts_au_user_id_53e813_idx'), models.Index(fields=['ip_address', 'endpoint'], name='accounts_au_ip_addr_9f13d8_idx')],
            },
        ),
    ]
