# Generated by Django 5.2.3 on 2025-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileobject",
            name="latest_version_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="s3_version_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
