# Generated by Django 5.2.3 on 2025-07-17 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_fileobject_latest_version_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fileobject",
            index=models.Index(
                fields=["owner", "parent"], name="files_fileo_owner_i_6f7090_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileobject",
            index=models.Index(
                fields=["parent", "name", "type"], name="files_fileo_parent__6f2733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileobject",
            index=models.Index(
                fields=["owner", "name", "type", "parent"],
                name="files_fileo_owner_i_fa31b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileobject",
            index=models.Index(
                fields=["parent", "type", "name"], name="files_fileo_parent__9630cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["file", "version_number"], name="files_filev_file_id_eeba2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["s3_version_id"], name="files_filev_s3_vers_5c9b7d_idx"
            ),
        ),
    ]
