# Generated by Django 5.2.3 on 2025-07-17 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_fileobject_files_fileo_owner_i_6f7090_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fileobject",
            name="files_fileo_owner_i_6f7090_idx",
        ),
        migrations.AddIndex(
            model_name="fileobject",
            index=models.Index(
                fields=["owner", "parent", "trashed_at"],
                name="files_fileo_owner_i_d9d129_idx",
            ),
        ),
    ]
