# Generated by Django 5.2.4 on 2025-07-18 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_fileobject_files_fileo_owner_i_6f7090_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredFile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starred_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_by', to='files.fileobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starred_at'],
                'unique_together': {('user', 'file')},
            },
        ),
    ]
