# Generated by Django 5.2.3 on 2025-07-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_starredfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="restore_status",
            field=models.CharField(default="available", max_length=20),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="storage_class",
            field=models.CharField(default="STANDARD", max_length=50),
        ),
    ]
