# Generated by Django 5.2.3 on 2025-08-04 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_fileversion_restore_status_fileversion_storage_class"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="initial_filename_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="FileActionLog",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("trashed", "Trashed"),
                            ("restored", "Restored"),
                            ("deleted", "Permanently deleted"),
                            ("created", "Created"),
                            ("modified", "Modified"),
                            ("shared", "Shared"),
                            ("unshared", "Unshared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="files.fileobject",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["file", "performed_at"],
                        name="files_filea_file_id_ec24f8_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "performed_at"],
                        name="files_filea_perform_7bb20e_idx",
                    ),
                ],
            },
        ),
    ]
