# Generated by Django 5.2.3 on 2025-07-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_starredfile"),
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileaccesscontrol",
            name="inherited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fileaccesscontrol",
            name="inherited_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inherited_shares",
                to="files.fileobject",
            ),
        ),
    ]
